import joy from './assets/album-joy-division.png';
import kendrick from './assets/album-kendrick-lamar.png';
import miles from './assets/album-miles-davis.png';
import tyler from './assets/album-tyler-creator.png';
import mia from './assets/album-mia.png';
import david from './assets/album-david-bowie.png';
import tame from './assets/album-tame-impala.png';
import johnny from './assets/album-johnny-cash.png';

export const albums = [
    {
        id: 'joy-division-unknown-pleasures',
        name: "Joy Division",
        title: "Unknown Pleasures",
        background: `url(${joy})`,
        year: '1979',
        tracks: '10',
        length: '39:28',
        trackList: [
            {
                id: "disorder",
                song: "Disorder",
                lyrics: [
                    "I've been waiting for a guide to come and take me by the hand,",
                    "Could these sensations make me feel the pleasures of a normal man?",
                    "These sensations barely interest me for another day,",
                    "I've got the spirit, lose the feeling, take the shock away.",
                    "It's getting faster, moving faster now, it's getting out of hand,",
                    "On the tenth floor, down the back stairs, it's a no man's land,",
                    "Lights are flashing, cars are crashing, getting frequent now,",
                    "I've got the spirit, lose the feeling, let it out somehow.",
                    "What means to you, what means to me, and we will meet again,",
                    "I'm watching you, I'm watching her, I'll take no pity from you friends,",
                    "Who is right, who can tell, and who gives a damn right now,",
                    "Until the spirit new sensation takes hold, then you know,",
                    "Until the spirit new sensation takes hold, then you know,",
                    "Until the spirit new sensation takes hold, then you know,",
                    "I've got the spirit, but lose the feeling,",
                    "I've got the spirit, but lose the feeling,",
                    "Feeling, feeling, feeling, feeling, feeling, feeling, feeling."
                ]
            },
            { id: "day-of-the-lords", song: "Day of the Lords", lyrics: [] },
            { id: "candidate", song: "Candidate", lyrics: [] },
            { id: "insight", song: "Insight", lyrics: [] },
            { id: "new-dawn-fades", song: "New Dawn Fades", lyrics: [] },
            {
                id: "she-s-lost-control",
                song: "She's Lost Control",
                lyrics: [
                    "Confusion in her eyes that says it all.",
                    "She's lost control.",
                    "And she's clinging to the nearest passer by,",
                    "She's lost control.",
                    "And she gave away the secrets of her past,",
                    "And said I've lost control again,",
                    "And a voice that told her when and where to act,",
                    "She said I've lost control again.",
                    "And she turned around and took me by the hand and said,",
                    "I've lost control again.",
                    "And how I'll never know just why or understand,",
                    "She said I've lost control again.",
                    "And she screamed out kicking on her side and said,",
                    "I've lost control again.",
                    "And seized up on the floor, I thought she'd die.",
                    "She said I've lost control.",
                    "She's lost control again.",
                    "She's lost control.",
                    "She's lost control again.",
                    "She's lost control.",
                    "Well I had to 'phone her friend to state my case,",
                    "And say she's lost control again.",
                    "And she showed up all the errors and mistakes,",
                    "And said I've lost control again.",
                    "But she expressed herself in many different ways,",
                    "Until she lost control again.",
                    "And walked upon the edge of no escape,",
                    "And laughed I've lost control.",
                    "She's lost control again.",
                    "She's lost control.",
                    "She's lost control again.",
                    "She's lost control."
                ]
            },
            { id: "shadowplay", song: "Shadowplay", lyrics: [] },
            { id: "wilderness", song: "Wilderness", lyrics: [] },
            { id: "interzone", song: "Interzone", lyrics: [] },
            { id: "i-remember-nothing", song: "I Remember Nothing", lyrics: [] }
        ],
    },

    {
        id: 'kendrick-lamar-to-pimp-a-butterfly',
        name: "Kendrick Lamar",
        title: "To Pimp a Butterfly",
        background: `url(${kendrick})`,
        year: '2015',
        tracks: '16',
        length: '78:51',
        trackList: [
            { id: "wesley-s-theory", song: "Wesley's Theory (feat. George Clinton and Thundercat)", lyrics: [] },
            { id: "for-free?", song: "For Free? (Interlude)", lyrics: [] },
            { id: "king-kunta", song: "King Kunta", lyrics: [] },
            { id: "institutionalized", song: "Institutionalized (feat. Bilal, Anna Wise and Snoop Dogg)", lyrics: [] },
            { id: "these-walls", song: "These Walls (feat. Bilal, Anna Wise and Thundercat)", lyrics: [] },
            { id: "u", song: "U", lyrics: [] },
            { id: "alright", song: "Alright", lyrics: [] },
            { id: "for-sale?", song: "For Sale? (Interlude)", lyrics: [] },
            { id: "momma", song: "Momma", lyrics: [] },
            { id: "hood-politics", song: "Hood Politics", lyrics: [] },
            { id: "how-much-a-dollar-cost", song: "How Much a Dollar Cost (feat. James Fauntleroy and Ronald Isley)", lyrics: [] },
            { id: "complexion", song: "Complexion (A Zulu Love) (feat. Rapsody)", lyrics: [] },
            { id: "the-blacker-the-berry", song: "The Blacker the Berry", lyrics: [] },
            { id: "you-ain-t-gotta-lie", song: "You Ain't Gotta Lie (Momma Said)", lyrics: [] },
            { id: "i", song: "I", lyrics: [] },
            { id: "mortal-man", song: "Mortal Man", lyrics: [] }
        ],
    },

    {
        id: 'miles-davis-bitches-brew',
        name: "Miles Davis",
        title: "Bitches Brew",
        background: `url(${miles})`,
        year: '1969',
        tracks: '6',
        length: '94:11',
        trackList: [
            { id: "pharaoh-s-dance", song: "Pharaoh's Dance", lyrics: [] },
            { id: "bitches-brew", song: "Bitches Brew", lyrics: [] },
            { id: "spanish-key", song: "Spanish Key", lyrics: [] },
            { id: "john-mclaughlin", song: "John McLaughlin", lyrics: [] },
            { id: "miles-runs-the-voodoo-down", song: "Miles Runs the Voodoo Down", lyrics: [] },
            { id: "sanctuary", song: "Sanctuary", lyrics: [] },
        ],
    },

    {
        id: 'tyler-the-creator-igor',
        name: "Tyler, The Creator",
        title: "Igor",
        background: `url(${tyler})`,
        year: '2019',
        tracks: '12',
        length: '39:43',
        trackList: [
            { id: "igor-s-theme", song: "Igor's Theme", lyrics: [] },
            { id: "earfquake", song: "Earfquake", lyrics: [] },
            { id: "i-think", song: "I think", lyrics: [] },
            { id: "exactly-what-you-run-from-you-end-up-chasing", song: "Exactly what you run from you end up chasing", lyrics: [] },
            { id: "running-out-of-time", song: "Running out of time", lyrics: [] },
            { id: "new-magic-wand", song: "New magic wand", lyrics: [] },
            { id: "a-boy-is-a-gun-*", song: "A boy is a gun*", lyrics: [] },
            { id: "puppet", song: "Puppet", lyrics: [] },
            { id: "what-s-good", song: "What's good", lyrics: [] },
            { id: "gone-gone-thank-you", song: "Gone, gone / Thank you", lyrics: [] },
            { id: "i-don-t-love-you-anymore", song: "I don't love you anymore", lyrics: [] },
            { id: "are-we-still-friends", song: "Are we still friends?", lyrics: [] },
        ],
    },
    {
        id: 'mia-kala',
        name: "Mia",
        title: "Kala",
        background: `url(${mia})`,
        year: '2007',
        tracks: '12',
        length: '47:32',
        trackList: [
            { id: "bamboo-banga", song: "Bamboo Banga", lyrics: [] },
            { id: "bird-flu", song: "Bird Flu", lyrics: [] },
            { id: "boyz", song: "Boyz", lyrics: [] },
            { id: "jimmy", song: "Jimmy", lyrics: [] },
            { id: "hussel", song: "Hussel (feat. Afrikan Boy)", lyrics: [] },
            { id: "mango-pickle-down-river", song: "Mango Pickle Down River (with The Wilcannia Mob)", lyrics: [] },
            { id: "20-dollar", song: "20 Dollar", lyrics: [] },
            { id: "world-town", song: "World Town", lyrics: [] },
            { id: "the-turn", song: "The Turn", lyrics: [] },
            { id: "xr2", song: "XR2", lyrics: [] },
            { id: "paper-planes", song: "Paper Planes", lyrics: [] },
        ],
    },
    {
        id: 'david-bowie-aladdin-sane',
        name: "David Bowie",
        title: "Aladdin Sane",
        background: `url(${david})`,
        year: '1973',
        tracks: '10',
        length: '40:47',
        trackList: [
            { id: "watch-that-man", song: "Watch That Man", lyrics: [] },
            { id: "aladdin-sane", song: "Aladdin Sane (1913–1938–197?)", lyrics: [] },
            { id: "drive-in-saturday", song: "Drive-In Saturday", lyrics: [] },
            { id: "panic-in-detroit", song: "Panic in Detroit", lyrics: [], },
            { id: "cracked-actor", song: "Cracked Actor", lyrics: [] },
            { id: "time", song: "Time", lyrics: [] },
            { id: "the-prettiest-star", song: "The Prettiest Star", lyrics: [] },
            { id: "let-s-spend-the-night-together", song: "Let's Spend the Night Together", lyrics: [] },
            { id: "the-jean-genie", song: "The Jean Genie", lyrics: [] },
            { id: "lady-grinning-soul", song: "Lady Grinning Soul", lyrics: [] }
        ],
    },
    {
        id: 'tame-impala-currents',
        name: "Tame Impala",
        title: "Currents",
        background: `url(${tame})`,
        year: '2015',
        tracks: '13',
        length: '51:12',
        trackList: [
            { id: "let-it-happen", song: "Let It Happen", lyrics: [], },
            { id: "nangs", song: "Nangs", lyrics: [] },
            { id: "the-moment", song: "The Moment", lyrics: [] },
            { id: "yes-i-m-changing", song: "Yes I'm Changing", lyrics: [] },
            { id: "eventually", song: "Eventually", lyrics: [] },
            { id: "gossip", song: "Gossip", lyrics: [] },
            { id: "the-less-i-know-the-better", song: "The Less I Know the Better", lyrics: [] },
            { id: "past-life", song: "Past Life", lyrics: [] },
            { id: "disciples", song: "Disciples", lyrics: [] },
            { id: "cause-i-m-a-man", song: "'Cause I'm a Man", lyrics: [] },
            { id: "reality-in-motion", song: "Reality in Motion", lyrics: [] },
            { id: "love-paranoia", song: "Love/Paranoia", lyrics: [] },
            { id: "new-person-same-old-mistakes", song: "New Person, Same Old Mistakes", lyrics: [] },
        ],
    },
    {
        id: 'johnny-cash-american-iv-the-man-comes-around',
        name: "Johnny Cash",
        title: "American IV: The Man Comes Around",
        background: `url(${johnny})`,
        year: '2002',
        tracks: '15',
        length: '51:52',
        trackList: [
            { id: "the-man-comes-around", song: "The Man Comes Around", lyrics: [] },
            { id: "hurt", song: "Hurt", lyrics: [] },
            { id: "give-my-love-to-rose", song: "Give My Love to Rose", lyrics: [] },
            { id: "bridge-over-troubled-water", song: "Bridge Over Troubled Water (with Fiona Apple)", lyrics: [] },
            { id: "i-hung-my-head", song: "I Hung My Head", lyrics: [] },
            { id: "the-first-time-i-ever-saw-your-face", song: "The First Time Ever I Saw Your Face", lyrics: [] },
            { id: "personal-jesus", song: "Personal Jesus", lyrics: [] },
            { id: "in-my-life", song: "In My Life", lyrics: [] },
            { id: "sam-hall", song: "Sam Hall", lyrics: [] },
            { id: "danny-boy", song: "Danny Boy", lyrics: [] },
            { id: "desperado", song: "Desperado (with Don Henley)", lyrics: [] },
            { id: "i-m-so-lonesome-i-could-cry", song: "I'm So Lonesome I Could Cry (duet with Nick Cave)", lyrics: [] },
            { id: "tear-stained-letter", song: "Tear Stained Letter", lyrics: [] },
            { id: "streets-of-laredo", song: "Streets of Laredo", lyrics: [] },
            { id: "we-ll-meet-again", song: "We'll Meet Again (with The Whole Cash Gang)", lyrics: [] },
        ],
    },
];

